version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      # Устанавливаем пароль именно для ROOT
      - MYSQL_ROOT_PASSWORD=root_password_here 
      
      # Имя базы данных, которая создастся при старте
      - MYSQL_DATABASE=booking_db
      
      # Создаем обычного пользователя (НЕ root!)
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password_here
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: